server:
  port: 80

spring:
  flyway:
    enabled: true
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:electronic-store-db
    username: cft
    password:
  h2:
    console:
      enabled: true
      path: /h2

